### ISSUE TITLE
Static subscribe method?

### ISSUE THREAD

**Issue by carsonfarmer** [tianzhao/rxjs#2]
Should this call be targeting the static method, rather than the instance method here? 
https://github.com/tianzhao/rxjs/blob/04c94c33ce7abc03ba289734c601c229d579e0ee/debugging/rxjs.js#L2565

**Comment by carsonfarmer** [comment]
To actually use _this_ version of `Subject` in tests and examples, I actually had to revert it to the top-level rsjs.js code:

```ts
...
connect() {
    if (!this.connected) {
      this.connected = true;
      this.source = this.observable?._subscribe(
        (x) => this._fire(x),
        { emit: (x) => this._fire(x) },
        new Progress(),
      );
    }
  }
...
```

**Comment by carsonfarmer** [comment]
It looks like the `delayWhen` has a similar type signature mismatch?

**Comment by tianzhao** [comment]
Yes, you are absolutely right on both errors. 
The calls should be made to Observable._subscribe(). 
The errors were fixed

Thank you!

**Comment by carsonfarmer** [comment]
_Thank you_!
